//! Builds the generic opcode stencils consumed by the baseline JIT.
//!
//! The selected `rustc` lowers typed forwarding functions to LLVM IR and then emits a
//! relocatable object. The IR remains in `OUT_DIR`; this script extracts the object functions
//! and relocations into a Rust module that is statically linked into `boa_engine`.

use object::{Object, ObjectSection, ObjectSymbol, RelocationKind, RelocationTarget};
use std::{
    env, fs,
    path::{Path, PathBuf},
    process::Command,
};

const OPCODE_COUNT: usize = 256;
const HANDLER_SYMBOL: &str = "boa_jit_handler";

fn main() {
    println!("cargo::rerun-if-changed=src/vm/opcode/mod.rs");
    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rustc-check-cfg=cfg(boa_jit_stencils)");
    if env::var_os("CARGO_FEATURE_JIT").is_none() {
        return;
    }
    let target = env::var("TARGET").expect("Cargo must set TARGET");
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").expect("Cargo must set target arch");
    let target_family = env::var("CARGO_CFG_TARGET_FAMILY").expect("Cargo must set target family");
    if target_arch != "x86_64" || target_family != "unix" {
        println!("cargo::warning=the baseline JIT is currently disabled for {target}");
        return;
    }
    generate(&target).unwrap_or_else(|error| panic!("could not build JIT stencils: {error}"));
    println!("cargo::rustc-cfg=boa_jit_stencils");
}

fn generate(target: &str) -> Result<(), String> {
    let out = PathBuf::from(env::var_os("OUT_DIR").ok_or("OUT_DIR is missing")?);
    let source = out.join("boa_jit_stencil_source.rs");
    let llvm_ir = out.join("boa_jit_stencils.ll");
    let object = out.join("boa_jit_stencils.o");
    fs::write(&source, template_source()).map_err(|e| e.to_string())?;
    let rustc = env::var_os("RUSTC").ok_or("RUSTC is missing")?;
    let emit = format!("llvm-ir={},obj={}", llvm_ir.display(), object.display());
    let output = Command::new(rustc)
        .args([
            "--crate-name",
            "boa_jit_stencils",
            "--crate-type=lib",
            "--edition=2024",
            "--target",
            target,
            "-Copt-level=3",
            "-Cpanic=abort",
            "-Crelocation-model=static",
            "-Ccode-model=large",
            "--emit",
            &emit,
        ])
        .arg(&source)
        .output()
        .map_err(|e| format!("failed to execute rustc: {e}"))?;
    if !output.status.success() {
        return Err(String::from_utf8_lossy(&output.stderr).into_owned());
    }
    extract_object(&object, &out.join("jit_stencils_generated.rs"))
}

fn template_source() -> String {
    let mut source = String::from(
        "#![no_std]\n\nunsafe extern \"Rust\" {\n    fn boa_jit_handler(context: *mut u8, pc: usize) -> u8;\n}\n\n",
    );
    for opcode in 0..OPCODE_COUNT {
        source.push_str(&format!(
            "#[unsafe(no_mangle)]\n#[inline(never)]\npub unsafe extern \"Rust\" fn boa_jit_stencil_{opcode:03}(context: *mut u8, pc: usize) -> u8 {{\n    unsafe {{ boa_jit_handler(context, pc) }}\n}}\n\n"
        ));
    }
    source
}

fn extract_object(object_path: &Path, generated_path: &Path) -> Result<(), String> {
    let data = fs::read(object_path).map_err(|e| e.to_string())?;
    let file = object::File::parse(&*data).map_err(|e| e.to_string())?;
    let mut generated = String::from("// @generated by core/engine/build.rs; do not edit.\n\n");
    for opcode in 0..OPCODE_COUNT {
        let name = format!("boa_jit_stencil_{opcode:03}");
        let symbol = file
            .symbols()
            .find(|s| s.name().ok() == Some(name.as_str()))
            .ok_or_else(|| format!("missing stencil symbol {name}"))?;
        let section_index = symbol
            .section_index()
            .ok_or_else(|| format!("{name} has no section"))?;
        let section = file
            .section_by_index(section_index)
            .map_err(|e| e.to_string())?;
        let section_data = section.data().map_err(|e| e.to_string())?;
        let start = (symbol.address() - section.address()) as usize;
        let end = start + symbol.size() as usize;
        let bytes = section_data
            .get(start..end)
            .ok_or_else(|| format!("invalid range for {name}"))?;
        let mut relocations = Vec::new();
        for (offset, relocation) in section.relocations() {
            let offset = offset as usize;
            if !(start..end).contains(&offset) {
                continue;
            }
            let RelocationTarget::Symbol(target) = relocation.target() else {
                return Err(format!("unsupported non-symbol relocation in {name}"));
            };
            let target = file.symbol_by_index(target).map_err(|e| e.to_string())?;
            let target_name = target.name().map_err(|e| e.to_string())?;
            if target_name != HANDLER_SYMBOL
                || relocation.kind() != RelocationKind::Absolute
                || relocation.size() != 64
            {
                return Err(format!(
                    "unsupported relocation in {name}: target={target_name}, kind={:?}, size={}",
                    relocation.kind(),
                    relocation.size()
                ));
            }
            relocations.push((offset - start, relocation.addend()));
        }
        if relocations.len() != 1 {
            return Err(format!(
                "{name} has {} relocations, expected one",
                relocations.len()
            ));
        }
        generated.push_str(&format!("static BYTES_{opcode:03}: &[u8] = &{bytes:?};\n"));
        let (offset, addend) = relocations[0];
        generated.push_str(&format!(
            "fn emit_{opcode:03}(code: &mut Vec<u8>, relocations: &mut Vec<PendingRelocation>) -> usize {{ emit_stencil(code, relocations, BYTES_{opcode:03}, {offset}, {addend}, {opcode}) }}\n"
        ));
    }
    generated.push_str("\npub(super) static EMITTERS: [Emitter; 256] = [\n");
    for opcode in 0..OPCODE_COUNT {
        generated.push_str(&format!("    emit_{opcode:03},\n"));
    }
    generated.push_str("];\n");
    fs::write(generated_path, generated).map_err(|e| e.to_string())
}
